server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tzl009/cloudTest.git
          searchPaths: config
          username: tzl009
          password: tzl19981017520l
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/